name: "forked"
on:
  pull_request:
    branches:
      - master
jobs:
  size_forked:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: forked
        uses: ./forked
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build