name: "forked"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - name: forked
        uses: ./forked/action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build